// Copyright (c) 2026 solar
// SPDX-License-Identifier: MIT

// Numeric values shared by rdp.h and rdplib.h.
#ifndef RDPLIB_CONSTANTS_H
#define RDPLIB_CONSTANTS_H

#include <stdint.h>

// The compiled clients preserve these values but not their original enum
// names.  RDP_* names describe recovered values.  RDPLIB_* names expose the
// same values through rdplib.h or describe results added by that interface.

// Recovered rdp_create flag word. Macros retain the required uint32_t values.
#define RDP_CREATE_ATTEMPT_BOTH UINT32_C(0x00000001)
#define RDP_CREATE_REQUIRE_IPV4 UINT32_C(0x00000002)
#define RDP_CREATE_REQUIRE_IPX UINT32_C(0x00000004)
#define RDP_CREATE_USE_CRC UINT32_C(0x40000000)
#define RDP_CREATE_USE_ENCRYPTION UINT32_C(0x80000000)

#define RDPLIB_USE_CRC RDP_CREATE_USE_CRC
#define RDPLIB_USE_ENCRYPTION RDP_CREATE_USE_ENCRYPTION

enum rdp_create_result
{
    RDP_CREATE_OK = 0,
    RDP_CREATE_FAILED = 1,
    RDP_CREATE_ALLOCATION_FAILED = 2,
    RDP_CREATE_REQUIRED_TRANSPORT_UNAVAILABLE = 10,
    RDP_CREATE_ADDRESS_IN_USE = 11
};

#define RDPLIB_ENDPOINT_CREATE_OK RDP_CREATE_OK
#define RDPLIB_ENDPOINT_CREATE_FAILED RDP_CREATE_FAILED
#define RDPLIB_ENDPOINT_CREATE_ALLOCATION_FAILED RDP_CREATE_ALLOCATION_FAILED
#define RDPLIB_ENDPOINT_CREATE_REQUIRED_TRANSPORT_UNAVAILABLE RDP_CREATE_REQUIRED_TRANSPORT_UNAVAILABLE
#define RDPLIB_ENDPOINT_CREATE_ADDRESS_IN_USE RDP_CREATE_ADDRESS_IN_USE

// Only KEEPALIVE is accepted by connection creation. Traceroute sets its bit internally.
#define RDP_CONNECTION_FEATURE_KEEPALIVE UINT32_C(0x00000001)
#define RDP_CONNECTION_FEATURE_TRACEROUTE UINT32_C(0x00000002)
// Normal rdplib starts with the recovered interval.  Source faithful scheduling keeps its literal expression.
#define RDPLIB_DEFAULT_KEEPALIVE_INTERVAL_MS UINT32_C(10000)
enum rdp_connect_result
{
    RDP_CONNECT_OK = 0,
    RDP_CONNECT_ALLOCATION_FAILED = 2,
    RDP_CONNECT_INVALID_ARGUMENT = 6,
    RDP_CONNECT_RESOLVE_FAILED = 12
};

#define RDPLIB_CONNECT_OK RDP_CONNECT_OK
#define RDPLIB_CONNECT_ALLOCATION_FAILED RDP_CONNECT_ALLOCATION_FAILED
#define RDPLIB_CONNECT_INVALID_ARGUMENT RDP_CONNECT_INVALID_ARGUMENT
#define RDPLIB_CONNECT_RESOLVE_FAILED RDP_CONNECT_RESOLVE_FAILED

enum rdp_send_flags
{
    RDP_SEND_UNRELIABLE = 0,
    RDP_SEND_RELIABLE = 1
};

#define RDPLIB_SEND_UNRELIABLE RDP_SEND_UNRELIABLE
#define RDPLIB_SEND_RELIABLE RDP_SEND_RELIABLE

typedef enum rdp_connection_send_result_t
{
    RDP_CONNECTION_SEND_OK = 0,
    RDP_CONNECTION_SEND_ALLOCATION_FAILED = 2,
    RDP_CONNECTION_SEND_INVALID_ARGUMENT = 6,
    RDP_CONNECTION_SEND_NOT_CONNECTED = 13,
    RDP_CONNECTION_SEND_BUFFER_FULL = 14,
    RDP_CONNECTION_SEND_HISTORY_FULL = 15,
    RDP_CONNECTION_SEND_FIN_SENT = 16,
    RDP_CONNECTION_SEND_PEER_STOPPED = 17,
    RDP_SEND_ERROR_TOO_BIG = 18
} rdp_connection_send_result_t;

#define RDPLIB_CONNECTION_SEND_OK RDP_CONNECTION_SEND_OK
#define RDPLIB_CONNECTION_SEND_ALLOCATION_FAILED RDP_CONNECTION_SEND_ALLOCATION_FAILED
#define RDPLIB_CONNECTION_SEND_INVALID_ARGUMENT RDP_CONNECTION_SEND_INVALID_ARGUMENT
#define RDPLIB_CONNECTION_SEND_NOT_CONNECTED RDP_CONNECTION_SEND_NOT_CONNECTED
#define RDPLIB_CONNECTION_SEND_BUFFER_FULL RDP_CONNECTION_SEND_BUFFER_FULL
#define RDPLIB_CONNECTION_SEND_HISTORY_FULL RDP_CONNECTION_SEND_HISTORY_FULL
#define RDPLIB_CONNECTION_SEND_FIN_SENT RDP_CONNECTION_SEND_FIN_SENT
#define RDPLIB_CONNECTION_SEND_PEER_STOPPED RDP_CONNECTION_SEND_PEER_STOPPED
#define RDPLIB_CONNECTION_SEND_PAYLOAD_TOO_LARGE RDP_SEND_ERROR_TOO_BIG

enum rdp_disconnect_reason
{
    RDP_DISCONNECT_REASON_PEER_RESET = 0x00010000,
    RDP_DISCONNECT_REASON_ICMP = 0x00030000,
    RDP_DISCONNECT_REASON_UNACKNOWLEDGED_MESSAGE = 0x00040000,
    RDP_DISCONNECT_REASON_CONNECTION_INACTIVITY = 0x00050000,
    RDP_DISCONNECT_REASON_PROTOCOL_ERROR = 0x00060000,
    RDP_DISCONNECT_REASON_SEND_ERROR = 0x00070000
};

#define RDPLIB_DISCONNECT_REASON_PEER_RESET RDP_DISCONNECT_REASON_PEER_RESET
#define RDPLIB_DISCONNECT_REASON_ICMP RDP_DISCONNECT_REASON_ICMP
#define RDPLIB_DISCONNECT_REASON_UNACKNOWLEDGED_MESSAGE RDP_DISCONNECT_REASON_UNACKNOWLEDGED_MESSAGE
#define RDPLIB_DISCONNECT_REASON_CONNECTION_INACTIVITY RDP_DISCONNECT_REASON_CONNECTION_INACTIVITY
#define RDPLIB_DISCONNECT_REASON_PROTOCOL_ERROR RDP_DISCONNECT_REASON_PROTOCOL_ERROR
#define RDPLIB_DISCONNECT_REASON_SEND_ERROR RDP_DISCONNECT_REASON_SEND_ERROR

enum rdp_packet_flags
{
    RDP_FLAG_SYSTEM = 0x0001,
    RDP_FLAG_ACKTHRU = 0x0004,
    RDP_FLAG_MASKOFFSET = 0x0008,
    RDP_FLAG_ACK_MASK_LENGTH = 0x00F0,
    RDP_FLAG_MULTI = 0x0100,
    RDP_FLAG_MSGID = 0x0200,
    RDP_FLAG_STOP = 0x0400,
    RDP_FLAG_FRAGMENT = 0x0800,
    RDP_FLAG_SEQUENCED = 0x1000,
    RDP_FLAG_SYN = 0x2000,
    RDP_FLAG_FIN = 0x4000,
    RDP_FLAG_RESET = 0x8000
};

enum
{
    RDP_STREAM_COUNT = 20,
    RDP_FRAGMENT_PAYLOAD_BYTES = 512,
    RDPLIB_STREAM_COUNT = RDP_STREAM_COUNT
};

// The callback receives an actual direction.  BOTH is an application mask.
typedef enum rdplib_packet_drop_direction_t
{
    RDPLIB_PACKET_DROP_INBOUND = 1,
    RDPLIB_PACKET_DROP_OUTBOUND = 2,
    RDPLIB_PACKET_DROP_BOTH = 3
} rdplib_packet_drop_direction_t;

// These negative errors belong only to the rdplib API.
enum rdplib_result
{
    RDPLIB_OK = 0,
    RDPLIB_ERROR_INVALID_ARGUMENT = -1,
    RDPLIB_ERROR_OUT_OF_MEMORY = -2,
    RDPLIB_ERROR_BUSY = -3,
    RDPLIB_ERROR_NOT_USABLE = -4,
    RDPLIB_ERROR_NOT_SUPPORTED = -5,
    RDPLIB_ERROR_PLATFORM = -6
};

#endif // RDPLIB_CONSTANTS_H
